// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnnQTB_nMOCSNrD_zvh1zdFLwaMUH3wY',
    appId: '1:973242895535:web:521bd962dd1143cad2d85a',
    messagingSenderId: '973242895535',
    projectId: 'financeiro-9cb44',
    authDomain: 'financeiro-9cb44.firebaseapp.com',
    storageBucket: 'financeiro-9cb44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnnQTB_nMOCSNrD_zvh1zdFLwaMUH3wY',
    appId: '1:973242895535:android:89bea8a65a615fd9d2d85a',
    messagingSenderId: '973242895535',
    projectId: 'financeiro-9cb44',
    storageBucket: 'financeiro-9cb44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnnQTB_nMOCSNrD_zvh1zdFLwaMUH3wY',
    appId: '1:973242895535:ios:dff3e1c028b4aaf0d2d85a',
    messagingSenderId: '973242895535',
    projectId: 'financeiro-9cb44',
    storageBucket: 'financeiro-9cb44.appspot.com',
    iosBundleId: 'com.example.financialManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnnQTB_nMOCSNrD_zvh1zdFLwaMUH3wY',
    appId: '1:973242895535:ios:dff3e1c028b4aaf0d2d85a',
    messagingSenderId: '973242895535',
    projectId: 'financeiro-9cb44',
    storageBucket: 'financeiro-9cb44.appspot.com',
    iosBundleId: 'com.example.financialManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnnQTB_nMOCSNrD_zvh1zdFLwaMUH3wY',
    appId: '1:973242895535:web:52a2548eaf830a7ed2d85a',
    messagingSenderId: '973242895535',
    projectId: 'financeiro-9cb44',
    authDomain: 'financeiro-9cb44.firebaseapp.com',
    storageBucket: 'financeiro-9cb44.appspot.com',
  );

}