// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5',
    appId: '1:210776833063:web:ae4b2cb32e97c84c682202',
    messagingSenderId: '210776833063',
    projectId: 'financialmanager-b0098',
    authDomain: 'financialmanager-b0098.firebaseapp.com',
    storageBucket: 'financialmanager-b0098.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5',
    appId: '1:210776833063:android:cc5dae2442af3955682202',
    messagingSenderId: '210776833063',
    projectId: 'financialmanager-b0098',
    storageBucket: 'financialmanager-b0098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5',
    appId: '1:210776833063:ios:faa1cfdb092a7c75682202',
    messagingSenderId: '210776833063',
    projectId: 'financialmanager-b0098',
    storageBucket: 'financialmanager-b0098.appspot.com',
    iosBundleId: 'com.example.financialManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5',
    appId: '1:210776833063:ios:faa1cfdb092a7c75682202',
    messagingSenderId: '210776833063',
    projectId: 'financialmanager-b0098',
    storageBucket: 'financialmanager-b0098.appspot.com',
    iosBundleId: 'com.example.financialManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5zQJ5',
    appId: '1:210776833063:web:427d6a26a3e5c011682202',
    messagingSenderId: '210776833063',
    projectId: 'financialmanager-b0098',
    authDomain: 'financialmanager-b0098.firebaseapp.com',
    storageBucket: 'financialmanager-b0098.appspot.com',
  );
}
